course_dates:
  start_date: "2026-9-8"
  end_date: "2026-12-10"
  day: "Wed"

lecture_order:
- 0_intro
- 1_vitals
- 2_glucose
- 3_respiratory
- 4_influenza
- 5_sleep
- 6_neonatal
- reading
- 7_neurodegen
- 8_mental
- 9_foundations
- 10_commentaries
- 11_presentations
- 12_reports

assignments:
  Proposal: 2_glucose
  Progress Report: 7_neurodegen
  Final Presentation: 11_presentations
  Final Report: 12_reports
